services:
  hugo:
    build:
      context: .
      dockerfile: dockerfile
    tty: true
    restart: always
    ports:
      - 32767:1313
    volumes:
      - ./:/src
    command: server --bind 0.0.0.0
