services:
  hugo:
    build:
      context: .
      dockerfile: dockerfile
    tty: true
    restart: unless-stopped
    ports:
      - 32767:1313
    volumes:
      - ./:/project
    command: server --bind 0.0.0.0
